### ISSUE TITLE
API page and right pane overlap making it hard to read

### ISSUE THREAD

**Issue by nvtkaszpir** [prometheus-operator/website#11] opened 2021-03-31 07:27 UTC
https://prometheus-operator.dev/docs/operator/api/#alertmanager
or even better under https://prometheus-operator.dev/docs/operator/api/#prometheusspec

![image](https://user-images.githubusercontent.com/1480252/113106782-72972f80-9203-11eb-9553-de718d54fa16.png)

**Comment by metalmatze** [comment] 2021-03-31 08:39
Thanks for reporting. This is a duplicate of #4

**Closed by metalmatze** 2021-03-31 08:39 UTC
